#! /bin/bash

web_application_dir='share/WebApplication'
translations_dir="${web_application_dir}/translations"

# pybabel extract -F babel.cfg -o messages.pot ${web_application_dir}
## pybabel extract -F babel.cfg -k lazy_gettext -o messages.pot .

# pybabel init -i messages.pot -d ${translations_dir} -l en

pybabel compile -d ${translations_dir}
pybabel update -i messages.pot -d ${translations_dir}

# End
