#! /bin/bash

web_application_dir='share/WebApplication'
translations_dir="${web_application_dir}/translations"

pybabel extract -F ${translations_dir}/babel.cfg -k lazy_gettext -o ${translations_dir}/messages.pot .

# pybabel init -i ${translations_dir}/messages.pot -d ${translations_dir} -l en
pybabel update -i ${translations_dir}/messages.pot -d ${translations_dir}

# End
